name: ESP32-S3 Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: espressif/idf:release-v5.1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build project
        shell: bash   # 用 bash 来兼容 [[ 语法
        run: |
          . /opt/esp/idf/export.sh
          cd $GITHUB_WORKSPACE  # 如果 CMakeLists.txt 不在根目录，这里改成你的项目目录
          idf.py set-target esp32s3 fullclean
          idf.py build -v
