name: Build ESP32-S3 + W5500 nanoFramework Firmware

on:
  push:
    branches: [ main]
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type'
        required: true
        default: 'Release'
        type: choice
        options:
        - Release
        - Debug
      upload_artifacts:
        description: 'Upload artifacts'
        required: false
        default: true
        type: boolean

env:
  ESP_IDF_VERSION: v5.2.3
  NANOFRAMEWORK_VERSION: latest

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        build_type: ["${{ github.event.inputs.build_type || 'Release' }}"]
        include:
          - build_type: Release
            cmake_build_type: MinSizeRel
            rtm: ON
            debugger: OFF
          - build_type: Debug
            cmake_build_type: Debug
            rtm: OFF
            debugger: ON
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        path: nanobuild-scripts

    - name: Checkout nanoFramework
      uses: actions/checkout@v4
      with:
        repository: nanoframework/nf-interpreter
        path: nf-interpreter
        submodules: recursive
        fetch-depth: 0

    - name: Setup Ubuntu Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git wget flex bison gperf python3 python3-pip \
          python3-setuptools python3.12-venv cmake ninja-build ccache \
          libffi-dev libssl-dev dfu-util libusb-1.0-0

    - name: Cache ESP-IDF
      uses: actions/cache@v3
      id: cache-esp-idf
      with:
        path: ~/esp/esp-idf
        key: ${{ runner.os }}-esp-idf-${{ env.ESP_IDF_VERSION }}
        restore-keys: |
          ${{ runner.os }}-esp-idf-

    - name: Install ESP-IDF
      if: steps.cache-esp-idf.outputs.cache-hit != 'true'
      run: |
        mkdir -p ~/esp
        cd ~/esp
        git clone -b ${{ env.ESP_IDF_VERSION }} --recursive https://github.com/espressif/esp-idf.git
        cd esp-idf
        ./install.sh esp32s3

    - name: Setup ESP-IDF Environment
      run: |
        echo "ESP_IDF_PATH=$HOME/esp/esp-idf" >> $GITHUB_ENV
        echo "PATH=$HOME/esp/esp-idf/tools:$PATH" >> $GITHUB_ENV

    - name: Copy Custom CMake Presets
      run: |
        cp nanobuild-scripts/CMakePresets-W5500.json nf-interpreter/CMakePresets.json

    - name: Configure CMake with Preset
      run: |
        cd nf-interpreter
        mkdir -p build
        
        source ~/esp/esp-idf/export.sh
        
        # 使用自定义预设，根据构建类型选择
        if [ "${{ matrix.build_type }}" = "Release" ]; then
          cmake --preset ESP32_S3_W5500_Release
        else
          cmake --preset ESP32_S3_W5500_Debug
        fi

    - name: Build Firmware
      run: |
        cd nf-interpreter/build
        cmake --build . -- -j$(nproc)

    - name: Calculate Firmware Size
      id: firmware_size
      run: |
        cd nf-interpreter/build
        SIZE=$(stat -c%s nanoCLR.bin)
        SIZE_MB=$(echo "scale=2; $SIZE/1024/1024" | bc)
        echo "size=$SIZE" >> $GITHUB_OUTPUT
        echo "size_mb=$SIZE_MB" >> $GITHUB_OUTPUT
        echo "Firmware size: ${SIZE_MB}MB ($SIZE bytes)"

    - name: Create Release Notes
      run: |
        cat > release-notes.md << 'EOF'
        # ESP32-S3 + W5500 nanoFramework Firmware
        
        ## Build Information
        - **Build Type**: ${{ matrix.build_type }}
        - **ESP-IDF Version**: ${{ env.ESP_IDF_VERSION }}
        - **nanoFramework Version**: ${{ env.NANOFRAMEWORK_VERSION }}
        - **Firmware Size**: ${{ steps.firmware_size.outputs.size_mb }}MB
        - **Build Date**: $(date -u)
        - **Commit**: ${{ github.sha }}
        
        ## Hardware Configuration
        - **Target**: ESP32-S3
        - **Ethernet**: W5500 SPI Module
        - **SPI Pins**:
          - SCLK: GPIO13
          - MISO: GPIO12
          - MOSI: GPIO11
          - CS: GPIO14
          - INT: GPIO10
          - RST: GPIO9
        
        ## Features
        - ${{ matrix.build_type == 'Release' && '✅ Production optimized (RTM enabled)' || '✅ Full debugging support' }}
        - ${{ matrix.build_type == 'Release' && '✅ Debugger disabled' || '✅ Debug symbols included' }}
        - ${{ matrix.build_type == 'Release' && '✅ Size optimized' || '✅ Visual Studio debugging' }}
        
        ## Usage
        1. Flash the firmware using nanoFramework Flash Tool
        2. Connect W5500 module according to pin configuration
        3. Use nanoFramework Visual Studio extension for development
        
        ## Downloads
        - Firmware: `nanoCLR.bin`
        - Release notes: `release-notes.md`
        EOF

    - name: Upload Firmware Artifact
      if: github.event.inputs.upload_artifacts != 'false'
      uses: actions/upload-artifact@v4
      with:
        name: nanoFramework-ESP32S3-W5500-${{ matrix.build_type }}-${{ github.sha }}
        path: |
          nf-interpreter/build/nanoCLR.bin
          nf-interpreter/build/nanoCLR.elf
          release-notes.md
        retention-days: 30

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/') && matrix.build_type == 'Release'
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ github.ref_name }}
        body_path: release-notes.md
        files: |
          nf-interpreter/build/nanoCLR.bin
          nf-interpreter/build/nanoCLR.elf
          release-notes.md
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Asset
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: nf-interpreter/build/nanoCLR.bin
        asset_name: nanoCLR-ESP32S3-W5500-${{ matrix.build_type }}-${{ github.ref_name }}.bin
        asset_content_type: application/octet-stream