name: Build ESP32-S3 W5500

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: espressif/idf:release-v5.1  # 固定版本

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache ESP-IDF dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.espressif
            ~/.cache
          key: ${{ runner.os }}-esp-idf-${{ hashFiles('**/CMakeLists.txt', '**/idf_component.yml') }}
          restore-keys: |
            ${{ runner.os }}-esp-idf-

      - name: Set target and clean build
        run: |
          . /opt/esp/idf/export.sh
          idf.py set-target esp32s3 fullclean

      - name: Build project
        run: |
          . /opt/esp/idf/export.sh
          idf.py build -v

      - name: Upload firmware binaries
        uses: actions/upload-artifact@v4
        with:
          name: firmware-binaries
          path: build/*.bin

      - name: Upload full build directory
        uses: actions/upload-artifact@v4
        with:
          name: build-directory
          path: build/
